<a href="https://colab.research.google.com/github/MehrajShah/PYTHON/blob/main/Numpy_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [2]:
#import numpy module with alias np

import numpy as np


We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [21]:
#: can create a NumPy ndarray object by using the array() function. To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

import numpy as np

# Create a NumPy ndarray object by passing a list into the array() function:
list_data = [1, 2, 3, 4, 5]
ndarray_from_list = np.array(list_data)

# Create a NumPy ndarray object by passing a tuple into the array() function:
tuple_data = (1, 2, 3, 4, 5)
ndarray_from_tuple = np.array(tuple_data)

# Create a NumPy ndarray object by passing an array-like object into the array() function:
array_like_data = np.arange(1, 6)
ndarray_from_array_like = np.array(array_like_data)

# Print the created ndarrays:
print("NumPy ndarray created from a list:\n", ndarray_from_list)
print("\nNumPy ndarray created from a tuple:\n", ndarray_from_tuple)
print("\nNumPy ndarray created from an array-like object:\n", ndarray_from_array_like)


NumPy ndarray created from a list:
 [1 2 3 4 5]

NumPy ndarray created from a tuple:
 [1 2 3 4 5]

NumPy ndarray created from an array-like object:
 [1 2 3 4 5]


In [22]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it



In [23]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it

import numpy as np

# Define a numpy array passing a list with 1,2 and 3 as elements in it
numpy_array = np.array([1, 2, 3])

# Print the numpy array
print(numpy_array)


[1 2 3]


In [24]:
# print output

print(numpy_array)


[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [25]:
#define a,b,c and d as instructed above
# # a =
# # b =
# # c =
# # d =

import numpy as np
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [26]:
#print dimentions of a,b, c and d

print(f"Dimension of a: {a.ndim}")
print(f"Dimension of b: {b.ndim}")
print(f"Dimension of c: {c.ndim}")
print(f"Dimension of d: {d.ndim}")


Dimension of a: 0
Dimension of b: 1
Dimension of c: 2
Dimension of d: 3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [27]:
# prompt: # print shape of each a,b ,c and d

print(f"Shape of a: {a.shape}")
print(f"Shape of b: {b.shape}")
print(f"Shape of c: {c.shape}")
print(f"Shape of d: {d.shape}")


Shape of a: ()
Shape of b: (3,)
Shape of c: (2, 3)
Shape of d: (2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [28]:
# print data type of c and d

print(f"Data type of c: {c.dtype}")
print(f"Data type of d: {d.dtype}")


Data type of c: int64
Data type of d: int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [29]:
#print type of a and b variable

print(f"Type of a: {type(a)}")
print(f"Type of b: {type(b)}")


Type of a: <class 'numpy.ndarray'>
Type of b: <class 'numpy.ndarray'>


In [31]:
# Lets check length of array b, using len() function
# # len(b)

print(f"Length of b: {len(b)}")


Length of b: 3


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

In [34]:

import numpy as np
# Define a numpy array passing a list with 1,2 and 3 as elements in it
numpy_array = np.array([1, 2, 3])

# Print the numpy array
print(numpy_array)

# Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention
print(f"Dimension of numpy_array: {numpy_array.ndim}")

# Lets print there shape as well. You can check shape using shape attribute
print(f"Shape of numpy_array: {numpy_array.shape}")

# Lets check data type passed in our array. To check data type you can use dtype attribute
print(f"Data type of numpy_array: {numpy_array.dtype}")

# Above output mean our array is having int type elements in it.
# Lets check the type of our variable. To check type of any numpy variable use type() function
print(f"Type of numpy_array: {type(numpy_array)}")

# Lets check length of array numpy_array, using len() function
print(f"Length of numpy_array: {len(numpy_array)}")


[1 2 3]
Dimension of numpy_array: 1
Shape of numpy_array: (3,)
Data type of numpy_array: int64
Type of numpy_array: <class 'numpy.ndarray'>
Length of numpy_array: 3


Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [35]:
# Define l1,l2,l3 and l4 as stated above.
# # l1 =
# # l2 =
# # l3 =
# # l4 =

import numpy as np
l1 = [10, 20, 30]
l2 = [40, 50, 60]
l3 = np.array(l1)
l4 = np.array(l2)


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [36]:
#code here as instructed above
%timeit [l1[i] * l2[i] for i in range(len(l1))]



917 ns ± 267 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [37]:
#Lets mulptiply l3 and l4
# Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

%timeit l3 * l4


783 ns ± 205 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [38]:
#Create a numpy array using arange with 1 and 11 as parameter in it

import numpy as np
np_array = np.arange(1,11)


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [39]:
# prompt: # Create an array using arange passing 1,11 and 2 as parameter in iter

import numpy as np
np_array = np.arange(1, 11, 2)


In [40]:
# prompt: # create numpy array using eye function with 3 as passed parameter

import numpy as np
np_array = np.eye(3)


In [41]:
# prompt: # Using arange() to generate numpy array x with numbers between 1 to 16
# # x=

import numpy as np
x = np.arange(1, 17)


In [42]:
# Reshape x with 2 rows and 8 columns

x = x.reshape(2,8)


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [43]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:

import numpy as np
x = np.arange(1, 17).reshape((2, 4, 2))


In [44]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4

import numpy as np
x = np.arange(1, 17).reshape(4, 4)
print(x)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [45]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
# y=


# print y



In [46]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
# # y=
# # print y

import numpy as np
x = np.arange(1, 17).reshape(2, 4, 2)
print(x)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [47]:
# Flattening y

y = x.flatten()
print(y)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [48]:
# Create an array a with all even numbers between 1 to 17
# # a =
# # print a

import numpy as np
a = np.arange(2, 18, 2)
print(a)


[ 2  4  6  8 10 12 14 16]


In [52]:
# Get third element in array a

print(a[2])


6


In [53]:
#Print 3rd, 5th, and 7th element in array

print(a[[2, 4, 6]])


[ 6 10 14]


Lets check the same for 2 D array

In [54]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
# # a =

import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [55]:
# prompt: # print the 3rd element from the 3rd row of a

print(a[2, 2])


9


Well done!

Now lets check indexing for 3 D array

In [56]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
# # b =

import numpy as np
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [57]:
 # Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.

print(b[1][0][2])


9


In [58]:
# Create 1D array
# # arr=

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])


In [59]:
# Slice elements from 1st to 5th element from the following array:

print(arr[1:5])


[2 3 4 5]


Note: The result includes the start index, but excludes the end index.



In [63]:
# Slice elements from index 5 to the end of the array:

print(arr[5:])


[6]


In [62]:
# Slice elements from the beginning to index 5 (not included):

print(arr[:5])


[1 2 3 4 5]


**STEP**

Use the step value to determine the step of the slicing:

In [64]:
 # Print every other element from index 1 to index 7:

print(arr[1:7:2])


[2 4 6]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [65]:
 # Return every other element from the entire array arr:

print(arr[::2])


[1 3 5]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [66]:
 # Print array a

print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'

print(a[2, 1:5])


[8 9]


In [68]:
# prompt: # In array 'a' print index 2 from all the elements :

print(a[:, 2])


[3 6 9]


In [69]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:

print(a[1:,:])


[[4 5 6]
 [7 8 9]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [70]:
 #x1=



In [72]:
import numpy as np
# Create a numpy array
x1 = np.array([1, 2, 3, 4, 5])

# Create a copy of x1 using copy() method
x2 = x1.copy()

# Create a view of x1 using view() method
x3 = x1.view()

# Modify x1
x1[0] = 10

# Print all the arrays
print("x1:", x1)
print("x2:", x2)
print("x3:", x3)


x1: [10  2  3  4  5]
x2: [1 2 3 4 5]
x3: [10  2  3  4  5]


In [73]:
# assign x2 = x1

x2 = x1


In [74]:
#print x1 and x2

print("x1:", x1)
print("x2:", x2)


x1: [10  2  3  4  5]
x2: [10  2  3  4  5]


Ok now you have seen that both of them are same

In [75]:
# change 1st element of x2 as 10

x2[0] = 10


In [76]:
#Again print x1 and x2

print("x1:", x1)
print("x2:", x2)


x1: [10  2  3  4  5]
x2: [10  2  3  4  5]


In [77]:
# Check memory share between x1 and x2

print(f"Memory share between x1 and x2: {x1.base is x2.base}")


Memory share between x1 and x2: True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [78]:
# Create a view of x1 and store it in x3.
# # x3 =

x3 = x1.view()


In [79]:
# Again check memory share between x1 and x3

print(f"Memory share between x1 and x3: {x1.base is x3.base}")


Memory share between x1 and x3: False


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [81]:
#Change 1st element of x3=100

x3[0] = 100


In [82]:
#print x1 and x3 to check if changes reflected in both

print("x1:", x1)
print("x3:", x3)


x1: [100   2   3   4   5]
x3: [100   2   3   4   5]


Now its proved.

Lets see how **Copy()** function works

In [83]:
# Now create an array x4 which is copy of x1
# # x4=

x4 = x1.copy()


In [84]:
# Change the last element of x4 as 900

x4[-1] = 900


In [85]:
# print both x1 and x4 to check if changes reflected in both

print("x1:", x1)
print("x4:", x4)


x1: [100   2   3   4   5]
x4: [100   2   3   4 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [86]:
 # Check memory share between x1 and x4

print("Memory share between x1 and x4: {x1.base is x4.base}")


Memory share between x1 and x4: {x1.base is x4.base}


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [87]:
# stack x1 and x4 along columns.

import numpy as np

x1 = np.array([1, 2, 3, 4, 5])
x4 = np.array([100, 200, 300, 400, 900])

# Stack x1 and x4 along columns
stacked_array = np.hstack((x1, x4))

# Print the stacked array
print(stacked_array)


[  1   2   3   4   5 100 200 300 400 900]


In [88]:
#stack x1 and x4 along rows

import numpy as np
x_stacked = np.hstack((x1, x4))
print(x_stacked)


[  1   2   3   4   5 100 200 300 400 900]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [91]:
# arr1 =
# # arr2 =
# ##join arr1 and arr2 along rows using concatenate() function

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

joined_array = np.concatenate((arr1, arr2), axis=0)
print(joined_array)

[1 2 3 4 5 6]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [92]:
# append arr2 to arr1

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr1 = np.append(arr1, arr2)
print(arr1)


[1 2 3 4 5 6]


Lets use insert() function which Inserts values into array before specified index value

In [93]:
# Inserts values into array x1 before index 4 with elements of x4

import numpy as np
x1 = np.array([1, 2, 3, 5, 6])
x4 = np.array([100, 200, 300, 400, 900])

x1 = np.insert(x1, 4, x4)
print(x1)


[  1   2   3   5 100 200 300 400 900   6]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [94]:
# delete 2nd element from array x2

import numpy as np
x2 = np.array([1, 2, 3, 4, 5])

# Delete the second element from the array using the np.delete() function
x2 = np.delete(x2, 1)

# Print the modified array
print(x2)


[1 3 4 5]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!

In [96]:
print("x2:", x2)


x2: [1 3 4 5]


In [97]:
print("Thanks & Regards\nMehraj Shah\n9622436070")


Thanks & Regards
Mehraj Shah
9622436070
